#!/usr/bin/env python

x = raw_input("Enter the first number: ")
y = raw_input("Enter the second number: ")

if int(x) > int(y):
    print "The maximum number is ", x
    print "The minimum number is ", y
    print "Maximum - minimum = ", int(x)-int(y)
else:
    print "The maximum number is ", y
    print "The minimum number is ", x
    print "Maximum - minimum = ", int(y)-int(x)
